#version: "3.8"
version: "3.5"

services:

  # MYSQL
  mysql__57:
    container_name: mysql__57
    restart: always
    build: ./57
    volumes:
      # директория с конфигурацией MySQL
      - ./57/conf.d:/etc/mysql/conf.d
      # сами БД
      - ./57/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PWD}
      MYSQL_USER: docker
      MYSQL_PASSWORD: ${DOCKER_PWD}
#      MYSQL_DATABASE: ${DB_NAME}
    ports:
     - "3306:3306"
    networks:
      backend:
        aliases:
          - mysql_net

networks:
  backend:
    external:
      name: local_backend